# Generated by Django 6.0.1 on 2026-01-31 18:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_employeedetails_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dead_line',
            field=models.DateField(default=datetime.date(2026, 1, 31)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='management.employeedetails'),
        ),
    ]
