# Generated by Django 6.0.1 on 2026-02-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_apihistory_remove_errorlog_user_id_errorlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apihistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
