# Generated by Django 6.0.1 on 2026-02-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_apihistory_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='management.skill'),
        ),
    ]
